# Everything qs_setup downloads is pinned here: fisher and every plugin to a
# commit, mise to a release checked against its sha256, and each mise tool to
# a version. Callers that pin this file (e.g. code-docker, by commit and
# sha256) therefore pin everything it installs, except qwreey-fish itself -
# pass --self qwreey/qwreey-fish@<commit> for that. Termux installs through
# pkg instead and isn't pinned.
#
# scripts/bump-pins.sh rewrites the block below: it resolves the latest
# versions, shows the upstream diff for review, and scripts/test-setup.sh
# checks the result in a fresh container. Don't hand-edit the block.

# --- pins: generated by scripts/bump-pins.sh ---
set -g _qs_pin_fisher 791da644d33d392216f6b1a9b5fc1e470db6d7f2
set -g _qs_pin_fisher_sha256 0fb6c81ae3003e95b5671766fa6c25c3597066e29965b7772f6c1b007387356d
set -g _qs_pin_plugins \
	qwreey/quietline-fish@d80886b242eeb87ec8c4c6593179654c7baf3035 \
	nickeb96/puffer-fish@83174b07de60078be79985ef6123d903329622b8 \
	jorgebucaran/autopair.fish@4d1752ff5b39819ab58d7337c69220342e9de0e2
set -g _qs_pin_mise 2026.9.16
set -g _qs_pin_mise_sha256 \
	linux-x64:b6f8757201f6a2ee799f45f3f52ef7ca0b4071523637dc3b0b24264dd3333518 \
	linux-arm64:acd7c94deb506567d1f8e2c65f4c154bc642e94497865c80bd370b2af6be7be2 \
	macos-x64:28268f494f1b142f503d1d7a988b680c6564bd4f3561919d96097b1198a38eae \
	macos-arm64:86cda8dde0fa9181706e825323dd8e26e96721a1b3cf37cbc610dd1680fecfda
set -g _qs_pin_tools \
	usage@6.12.0 \
	eza@0.23.5 \
	gdu@5.37.0 \
	gitui@0.28.1 \
	duf@0.9.1 \
	btop@1.4.7 \
	bat@0.26.1 \
	jq@1.8.2 \
	fzf@0.74.4 \
	fd@10.5.0 \
	ripgrep@15.2.0 \
	carapace@1.8.0
# --- end pins ---

# mise packages that don't have a working build for Termux/Android and
# have no native Termux package either; just skip them there.
set -g _qs_mise_termux_ignore usage btop

# mise packages that don't have a working build for Termux/Android but do
# have a native Termux package; install these via `pkg` there instead.
# Format: misepkgname:pkgname
set -g _qs_mise_termux_native \
	eza:eza gdu:gdu gitui:gitui duf:duf bat:bat jq:jq fzf:fzf fd:fd ripgrep:ripgrep

function _qs_mise_termux_native_lookup --argument-names pkgname
	for entry in $_qs_mise_termux_native
		set -l parts (string split ":" $entry)
		test "$parts[1]" = "$pkgname"
		and echo $parts[2]
		and return 0
	end
	return 1
end

# "eza" -> "eza@0.23.5" from $_qs_pin_tools. A tool with no pin is an error,
# not a silent latest: bump-pins.sh only moves pins that already exist.
function _qs_pinned_tool --argument-names name
	for spec in $_qs_pin_tools
		if test (string split -m1 @ -- $spec)[1] = "$name"
			echo $spec
			return 0
		end
	end
	echo "qs_setup: $name has no pin in _qs_pin_tools - not installing it (add $name@<version> to the pins block first)" >&2
	return 1
end

function _qs_sha256 --argument-names file
	if command --query sha256sum
		sha256sum $file | string split -f1 ' '
	else
		shasum -a 256 $file | string split -f1 ' '
	end
end

# Downloads url to a temp file and prints its path - only if the content
# hashes to sha256. Nothing unverified is ever left behind to be run.
function _qs_fetch_verified --argument-names url sha256
	set -l tmp (mktemp)
	if not curl -fsSL -o $tmp $url
		echo "qs_setup: download failed: $url" >&2
		rm -f $tmp
		return 1
	end
	set -l actual (_qs_sha256 $tmp)
	if test "$actual" != "$sha256"
		echo "qs_setup: checksum mismatch for $url (expected $sha256, got $actual) - not using it" >&2
		rm -f $tmp
		return 1
	end
	echo $tmp
end

# True if version a is newer than b ("2026.10.1" vs "2026.9.16").
function _qs_version_newer --argument-names a b
	set -l x (string split . -- $a)
	set -l y (string split . -- $b)
	for i in (seq (math max (count $x), (count $y)))
		set -l p 0
		set -l q 0
		set -q x[$i]; and string match -qr '^[0-9]+$' -- $x[$i]; and set p $x[$i]
		set -q y[$i]; and string match -qr '^[0-9]+$' -- $y[$i]; and set q $y[$i]
		test $p -gt $q; and return 0
		test $p -lt $q; and return 1
	end
	return 1
end

# The name fisher records spec under: a local path resolved, anything else
# lower-cased (fisher does the same).
function _qs_fisher_name --argument-names spec
	if test -e "$spec"
		realpath $spec
	else
		string lower -- $spec
	end
end

# Replaces installed fisher plugin old with spec. fisher treats a different
# @ref (or a path) as a different plugin and won't install over the files the
# old one owns, but remove + install would leave nothing behind if the
# download then fails (network, GitHub's 60/hour API limit). So the entry is
# renamed to spec and *updated* instead: fisher only deletes the old files
# once the new ones have arrived, and returns non-zero when it updated
# nothing - then the old name is put back so the next run retries.
function _qs_fisher_swap --argument-names old spec
	set -l new (_qs_fisher_name $spec)
	set -l index (contains --index -- $old $_fisher_plugins)
	or return 1
	set -l old_var _fisher_(string escape --style=var -- $old)_files
	set -l new_var _fisher_(string escape --style=var -- $new)_files
	set -U $new_var $$old_var
	set -U _fisher_plugins[$index] $new
	set -e -U $old_var
	fisher update $new
	and return 0

	echo "qs_setup: could not fetch $spec - keeping $old" >&2
	set -U $old_var $$new_var
	set -e -U $new_var
	set -U _fisher_plugins[$index] $old
	# fisher already rewrote fish_plugins with the new name.
	set -l list $__fish_config_dir/fish_plugins
	if test -e $list
		string replace -- (string replace -- $HOME \~ $new) (string replace -- $HOME \~ $old) <$list >$list.qs_tmp
		and mv -f $list.qs_tmp $list
	end
	return 1
end

# Installs spec ("owner/repo@commit"), replacing whichever ref of the same
# repo is installed now.
function _qs_fisher_pin --argument-names spec
	set -l want (_qs_fisher_name $spec)
	contains -- $want $_fisher_plugins
	and return 0
	set -l repo (string split -m1 @ -- $want)[1]
	for p in $_fisher_plugins
		if test (string split -m1 @ -- $p)[1] = $repo
			_qs_fisher_swap $p $spec
			return
		end
	end
	fisher install $spec
end

# Installs qwreey-fish as spec. The copy it replaces may be installed under
# another name entirely (a local checkout's path, or the other way around),
# not just another @ref, so it's found by the file it owns instead. Replacing
# it re-sources this file, redefining every function here mid-run - so this
# goes last.
function _qs_fisher_pin_self --argument-names spec
	contains -- (_qs_fisher_name $spec) $_fisher_plugins
	and return 0
	for p in $_fisher_plugins
		set -l files_var _fisher_(string escape --style=var -- $p)_files
		if string match -q -- '*/functions/qs_setup.fish' $$files_var
			_qs_fisher_swap $p $spec
			return
		end
	end
	fisher install $spec
end

# Wrapper around `mise use -g` that pins each name (see _qs_pinned_tool) and,
# on Termux, drops packages in $_qs_mise_termux_ignore and installs packages
# in $_qs_mise_termux_native via `pkg` instead of mise.
function _qs_mise_use
	set -l result 0
	set -l mise_packages
	set -l native_packages
	for pkgname in $argv
		if set -q TERMUX_VERSION
			contains -- $pkgname $_qs_mise_termux_ignore
			and continue
			set -l native_name (_qs_mise_termux_native_lookup $pkgname)
			if test $status -eq 0
				set -a native_packages $native_name
				continue
			end
		end
		if set -l spec (_qs_pinned_tool $pkgname)
			set -a mise_packages $spec
		else
			set result 1
		end
	end

	if test (count $native_packages) -gt 0
		pkg install -y $native_packages
		or set result 1
	end
	if test (count $mise_packages) -gt 0
		mise use -g $mise_packages
		or set result 1
	end
	return $result
end

# Puts the pinned mise release at dest. A mise that is already at the pin is
# left alone, and so is a newer one (updated on purpose - qs_update is how
# the pin itself moves forward).
function _qs_install_mise --argument-names dest
	if test -x $dest
		set -l have (string split -f1 ' ' -- ($dest --version 2>/dev/null)[1])
		if test "$have" = "$_qs_pin_mise"
			return 0
		end
		if _qs_version_newer "$have" $_qs_pin_mise
			echo "qs_setup: keeping mise $have (newer than the pinned $_qs_pin_mise)"
			return 0
		end
	end

	set -l os
	switch (uname -s)
		case Linux
			set os linux
		case Darwin
			set os macos
		case '*'
			echo "qs_setup: no pinned mise build for "(uname -s) >&2
			return 1
	end
	set -l arch
	switch (uname -m)
		case x86_64 amd64
			set arch x64
		case aarch64 arm64
			set arch arm64
		case '*'
			echo "qs_setup: no pinned mise build for "(uname -m) >&2
			return 1
	end
	set -l sha256
	for entry in $_qs_pin_mise_sha256
		set -l kv (string split -m1 : -- $entry)
		test "$kv[1]" = "$os-$arch"
		and set sha256 $kv[2]
	end
	if test -z "$sha256"
		echo "qs_setup: no pinned mise checksum for $os-$arch" >&2
		return 1
	end

	set -l url https://github.com/jdx/mise/releases/download/v$_qs_pin_mise/mise-v$_qs_pin_mise-$os-$arch
	set -l tmp (_qs_fetch_verified $url $sha256)
	or return 1
	mkdir -p (path dirname $dest)
	chmod +x $tmp
	mv -f $tmp $dest
	echo "qs_setup: installed mise $_qs_pin_mise to $dest"
end

function _qs_setup_mise
	# Install & check mise to standard path
	if set -q TERMUX_VERSION
		# Termux ships mise as a pkg; install/upgrade through pkg and point at its binary
		pkg install -y mise
		set -f MISE_INSTALL_PATH "$PREFIX/bin/mise"
	else
		set -q MISE_INSTALL_PATH
		or set -f MISE_INSTALL_PATH "$HOME/.local/bin/mise"
		_qs_install_mise $MISE_INSTALL_PATH
		or return 1
	end

	# Create mise activate conf
	# set -l mise_script "$($MISE_INSTALL_PATH activate fish | string replace -- "$HOME" "\$HOME")"
	# eval "$mise_script"
	echo "eval \"\$($MISE_INSTALL_PATH activate fish)\"" > "$__fish_config_dir/conf.d/20-mise_activate.fish"
	eval "$($MISE_INSTALL_PATH activate fish)"
end

function _qs_setup_carapace
	set -Ux CARAPACE_BRIDGES 'zsh,fish,bash,inshellisense'
	_qs_mise_use carapace
	set -l carapace_script "$(carapace _carapace fish | string replace -- "$HOME" "\$HOME")"
	echo "$carapace_script" > "$__fish_config_dir/conf.d/30-carapace_activate.fish"
	eval "$carapace_script"
end

# Loads fisher from the pinned, checksummed fisher.fish, then has it install
# (or swap itself to) the same commit.
function _qs_setup_fisher
	set -l spec jorgebucaran/fisher@$_qs_pin_fisher
	if functions --query fisher; and contains -- $spec $_fisher_plugins
		return 0
	end
	set -l url https://raw.githubusercontent.com/jorgebucaran/fisher/$_qs_pin_fisher/functions/fisher.fish
	set -l tmp (_qs_fetch_verified $url $_qs_pin_fisher_sha256)
	or return 1
	source $tmp
	rm -f $tmp
	_qs_fisher_pin $spec
end

function _qs_setup_bin
	# aqua:ogham/dog not works
	_qs_mise_use eza gdu gitui duf btop bat jq fzf fd ripgrep
end

function _qs_setup_plugin --argument-names self
	set -l result 0
	for spec in $_qs_pin_plugins
		_qs_fisher_pin $spec
		or set result 1
	end
	_qs_fisher_pin_self $self
	or set result 1
	return $result
end

function qs_setup; argparse --max-args 0 \
	'with-carapace' \
	'without-mise' \
	'without-bin' \
	'self=' \
-- $argv
	or return
	# Which qwreey-fish to install: a fisher spec, e.g. qwreey/qwreey-fish@<commit>
	# to match a pinned copy of this file, or a local checkout's path.
	set -l self qwreey/qwreey-fish
	set -q _flag_self
	and set self $_flag_self

	# Every step runs even if an earlier one failed (each says why on
	# stderr); the exit status says whether anything did.
	set -l result 0
	_qs_setup_fisher
	or return 1
	if not set -q _flag_without_mise
		if _qs_setup_mise
			# for mise autocomplete
			_qs_mise_use usage
			or set result 1
			if not set -q _flag_without_bin
				_qs_setup_bin
				or set result 1
			end
			if set -q _flag_with_carapace
				_qs_setup_carapace
				or set result 1
			end
		else
			set result 1
		end
	end
	# Last: installing qwreey-fish re-sources this file, and everything above
	# should run with the pins of the copy that was actually verified.
	_qs_setup_plugin $self
	or set result 1
	return $result
end
